// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AspirationTag: typeof import('./src/components/AspirationTag.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GenderIcon: typeof import('./src/components/GenderIcon.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
    TraitTag: typeof import('./src/components/TraitTag.vue')['default']
    CarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    IcomoonFreeDiamonds: typeof import('virtual:vite-icons/icomoon-free/diamonds')['default']
    CarbonLocation: typeof import('virtual:vite-icons/carbon/location')['default']
    CarbonHome: typeof import('virtual:vite-icons/carbon/home')['default']
    CarbonPedestrian: typeof import('virtual:vite-icons/carbon/pedestrian')['default']
    CarbonWarning: typeof import('virtual:vite-icons/carbon/warning')['default']
    CarbonEarth: typeof import('virtual:vite-icons/carbon/earth')['default']
    CarbonCampsite: typeof import('virtual:vite-icons/carbon/campsite')['default']
    CarbonGenderFemale: typeof import('virtual:vite-icons/carbon/gender-female')['default']
    CarbonGenderMale: typeof import('virtual:vite-icons/carbon/gender-male')['default']
    CarbonTransgender: typeof import('virtual:vite-icons/carbon/transgender')['default']
  }
}

export { }
