// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    GenderIcon: typeof import('./src/components/GenderIcon.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
    IcomoonFreeDiamonds: typeof import('virtual:vite-icons/icomoon-free/diamonds')['default']
    CarbonCampsite: typeof import('virtual:vite-icons/carbon/campsite')['default']
    CarbonHome: typeof import('virtual:vite-icons/carbon/home')['default']
    CarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    CarbonGenderFemale: typeof import('virtual:vite-icons/carbon/gender-female')['default']
    CarbonGenderMale: typeof import('virtual:vite-icons/carbon/gender-male')['default']
    CarbonTransgender: typeof import('virtual:vite-icons/carbon/transgender')['default']
  }
}

export { }
